### ISSUE TITLE
Downloading large Raw Results files results in Varnish error

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-core#245]
For example, http://results.openelections.net/pa/raw/20121106__pa__general__precinct__raw.csv

![screen shot 2014-12-21 at 4 29 00 pm](https://cloud.githubusercontent.com/assets/2214/5519742/7f8c6b7c-892e-11e4-834c-b000828b0de8.png)

**Comment by dwillis** [comment]
@zstumgoren can we close this, or should we leave it open?

**Comment by zstumgoren** [comment]
Please leave open. Temp fix is in place but I need to implement permanent
fix. I'll close when complete.

**Comment by zstumgoren** [comment]
Varnish vcl fix puppetized in openelex-config repo and applied to production.
