### ISSUE TITLE
If someone wanted to contribute to pulling data, how would they?

### ISSUE THREAD

**Issue by jackiekazil** [openelections/openelections-core#251]
If someone wanted to contribute to pulling data, how would they?
Specifically, what work needs to be done here: https://github.com/openelections/openelections-core/tree/dev/openelex/us

**Comment by dwillis** [comment]
Hey @jackiekazil, thanks for asking! There are a couple of ways to contribute. For example, [our guide to contributing code](http://docs.openelections.net/guide/) will help get you up to speed on our processes and environment. In terms of what's needed, the easiest thing to do is to take a state and start to create a state-specific module in the `core` repo. You could work on an existing state in progress, like Georgia, or take a state that hasn't been started (say, Wisconsin).

Another way is by finding and pre-processing data (usually from PDFs or other formats), like we've done in states like MS, PA and NV. That could involve writing scrapers or extracting data from PDFs and getting it into an `openelections-data-{state}` repository so that we can get the data into our processing pipeline. Happy to get you started on something and answer more questions.

**Comment by jackiekazil** [comment]
I should have been more specific. I wanted to give an extra challenge for folks that I am teaching who might be more advanced. Is there anything specific to webscraping that you could call out? 
(Here is the tutorial that I am teaching w/ @Sisiwei: https://us.pycon.org/2015/schedule/presentation/318/)

**Comment by dwillis** [comment]
Oh, I'm sure I could come up with a few things, yes! I'll post some specific targets here.

**Comment by jackiekazil** [comment]
:-) Thank you!

**Comment by dwillis** [comment]
Scrapers, in order of difficulty:

* [Ohio 2000 results](http://www.sos.state.oh.us/sos/elections/Research/electResultsMain/2000ElectionsResults.aspx) or [Ohio 2002 results](http://www.sos.state.oh.us/sos/elections/Research/electResultsMain/2002Results.aspx) (by race, scraping tables for each link)
* Michigan election results by county for [2014 general](http://miboecfr.nictusa.com/election/results/14GEN/), [2014 primary](http://miboecfr.nictusa.com/election/results/14PRI/), all 2013 elections
* Multnomah County (Ore.) precinct results for [2014 general](https://multco.us/elections/november-2014-election-precinct-results), [2014 primary](https://multco.us/elections/may-2014-primary-election-precinct-results-0), [2012 general](https://multco.us/elections/november-2012-general-election-abstract-votes-precinct-level), [2012 primary](https://multco.us/elections/may-2012-primary-election-abstract-votes-precinct-level), [2012 special](https://multco.us/elections/january-31-2012-special-election-abstract-votes-0).
* South Carolina precinct results from 2000-2006 (drill down from [here](http://www.scvotes.org/statistics/election_returns_from_primaries_and_general_elections_statewide))

**Comment by dwillis** [comment]
There's nothing required in terms of output; we'll take as much as folks are able to do. But ideally it would yield text (either in files or Python objects).

**Comment by sisiwei** [comment]
These are fantastic.

Plus we're showing them OpenElections as an example of why one scrapes at
all, so it'd be great to have the students contribute.

On Mon, Apr 6, 2015 at 11:19 AM, Derek Willis <notifications@github.com>
wrote:

> Scrapers, in order of difficulty:
>
>    - Ohio 2000 results
>    <http://www.sos.state.oh.us/sos/elections/Research/electResultsMain/2000ElectionsResults.aspx>
>    or Ohio 2002 results
>    <http://www.sos.state.oh.us/sos/elections/Research/electResultsMain/2002Results.aspx>
>    (by race, scraping tables for each link)
>    - Michigan election results by county for 2014 general
>    <http://miboecfr.nictusa.com/election/results/14GEN/>, 2014 primary
>    <http://miboecfr.nictusa.com/election/results/14PRI/>, all 2013
>    elections
>    - Multnomah County (Ore.) precinct results for 2014 general
>    <https://multco.us/elections/november-2014-election-precinct-results>, 2014
>    primary
>    <https://multco.us/elections/may-2014-primary-election-precinct-results-0>,
>    2012 general
>    <https://multco.us/elections/november-2012-general-election-abstract-votes-precinct-level>,
>    2012 primary
>    <https://multco.us/elections/may-2012-primary-election-abstract-votes-precinct-level>,
>    2012 special
>    <https://multco.us/elections/january-31-2012-special-election-abstract-votes-0>
>    .
>    - South Carolina precinct results from 2000-2006 (drill down from here
>    <http://www.scvotes.org/statistics/election_returns_from_primaries_and_general_elections_statewide>
>    )
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openelections/openelections-core/issues/251#issuecomment-90100845>
> .
>



-- 
Sisi Wei
News Applications Developer
ProPublica
sisiwei.com // @sisiwei

**Comment by jackiekazil** [comment]
YAY! :us:
