### ISSUE TITLE
Port to Python 3 by 2020

### ISSUE THREAD

**Issue by nealmcb** [openelections/openelections-core#260]
Python 2 will no longer be supported as of 2020.
Python 3 is a better language, and all the major libraries support it now.
So we want to port to Python 3, as convenient, over the next few years.

Background and nice timeline diagram at http://www.python3statement.org/

Great advice, planning process, tips at at [Porting Python 2 Code to Python 3](https://docs.python.org/3/howto/pyporting.html)

> To make your project be single-source Python 2/3 compatible, the basic steps are:

  1. Only worry about supporting Python 2.7
  2. Make sure you have good test coverage ([coverage.py](https://pypi.python.org/pypi/coverage) can help; `pip install coverage`)
  3. Learn the differences between Python 2 & 3
  4. Use [Futurize](http://python-future.org/automatic_conversion.html) (or [Modernize](https://python-modernize.readthedocs.org/en/latest/)) to update your code (e.g. `pip install future`)
  5. Use [Pylint](https://pypi.python.org/pypi/pylint) to help make sure you don't regress on your Python 3 support (`pip install pylint`)
  6. Use [caniusepython3](https://pypi.python.org/pypi/caniusepython3) to find out which of your dependencies are blocking your use of Python 3 (`pip install caniusepython3`)
  7. Once your dependencies are no longer blocking you, use continuous integration to make sure you stay compatible with Python 2 & 3 ([tox](https://pypi.python.org/pypi/tox) can help test against multiple versions of Python; `pip install tox`)
  8. Consider using optional static type checking to make sure your type usage works in both Python 2 & 3 (e.g. use [mypy](http://mypy-lang.org/) to check your typing under both Python 2 & Python 3).

**Comment by psa** [comment]
README.md suggests the project is developed in Python 3. Anything left to do here?

**Comment by nealmcb** [comment]
Thanks @psa.  Seems it was fixed in #276
