### ISSUE TITLE
Precinct location information

### ISSUE THREAD

**Issue by adamConnerSax** [openelections/openelections-core#278]
This effort and data is amazing!!

Has there been any effort to add more specific geographic information about the precinct locations?  An address or zip-code or census tract FIPS?

I tried a couple of google searches using "PRECINCT-PLACE-NAME in COUNTY, STATE" and they worked in that they provided an address.  So I could imagine how that data might get gathered.  But I was wondering if someone had already done that. 

If not, how would that data best be organized?  A CSV file per state with "PLACE NAME, ZIPCODE, CENSUS FIPS, LAT, LONG, STREET 1, STREET 2, CITY"?

My interest is actually joining the precinct data with State Legislative Districts so if there's a direct way to do that, I could skip the geolocation part.

**Comment by dwillis** [comment]
@adamConnerSax For our part, no, we haven't tried to maintain geographic information about precincts because they frequently change from election to election. But if you're interested in state legislative districts, you might be able to just isolate the precincts within specific districts within the data and work from there?

**Comment by adamConnerSax** [comment]
Right.  But how do I know which precincts are in which State Leg District (SLD)?  

For any state of interest I'd like to be able to aggregate the precinct results for some statewide or national election into an SLD-level result for that election (as input to a model for the closeness of an election for the state-legislature in that district).  

And I'd like to be able to do it for *all the SLDs in all the states*. 

Suppose the google lookup worked.  And I am willing to figure out how to do it in bulk from all the place names.  Given that precincts move around, what would be the most stable way to supplement the data you collect?  Would a csv file of the sort described above work?  Is the same place ever named differently in different years?  I guess that might be okay since the data would only be used to go from State + PLaceName to address.

Anyway, I'm going to look into doing the bulk google search and,if it works, I'd like to make the results useful to other people using your data so I'm interested in any thoughts you have in that direction!

**Comment by dwillis** [comment]
@adamConnerSax Here's one way: the results data for individual state legislative districts includes the precinct identifier, so you can take that info from our results for state senate or state house races and compile a list of precincts in each district that way. The folks at DailyKos Elections do this quite well.

**Comment by adamConnerSax** [comment]
That's a great idea!  Thanks.  I'll try it in the couple of weeks...

**Comment by adamConnerSax** [comment]
So I've tried it some.  It works pretty well in GA but not so well in TX or IA.  The issue is that some precincts don't have state races listed in the general election.  I thought I would tackle this by loading older general elections, or, as you suggested, using state elections to make the mappings.  But the precinct names sometimes change in between the state election and the general or the primary and the general or whatever. So I'm failing to map all the precincts to state legislative districts.  I might try a "fuzzy" match on strings to see if I can get more precincts matched but some are pretty different:

For example, in IA, in the general in Allamakee county there is a precinct labeled "LT/PC/WV CITY" and somehow Allamakee has no state senate races in listed in the general election.  But in the state primaries, that precinct is listed as "Pct 5-Waterville Library PC/LT/WV CITY".  I can certainly match these by hand but there are a hundred or so in IA and way more in TX. 

And things are weirder in TX.  Lots of precincts are just numbers and they don't seem to be the same from 2016 to 2018.  So fuzzy matching won't help there.  

Do you have any other thoughts about how to tackle this?

**Comment by adamConnerSax** [comment]
Fuzzy matching helps some in IA but is useless in TX where precincts are often just numbers which don't match at all between elections (see Bexar county).

Is every state house district wholly contained in one state senate district?  Does that vary from state to state?

BTW, I'm not sure if you are interested in the output of this aggregation.  I'm more than happy to share.

It's all here so far: https://github.com/blueripple/openelections

**Comment by dwillis** [comment]
A couple of thoughts:

1. To do what you're wanting in Texas, I would suggest you use the data produced by the [Texas Legislative Council](https://data.capitol.texas.gov/dataset/vtds), which should be consistent.

2. Many state house districts are wholly contained within a single senate district, but there are lots that are not. This absolutely varies from state to state.

**Comment by adamConnerSax** [comment]
Thanks!  I'll look into that source for Texas.   Though it turns out Daily Kos is pretty caught up for Texas.  So maybe I can use that.  IA is still something of a puzzle....
