### ISSUE TITLE
License for data

### ISSUE THREAD

**Issue by hroest** [openelections/openelections-core#279]
I just discovered this project and it looks great, however I cannot seem to find the license for the data itself. I can see the license for the code, but under which license is the data itself published? Unfortunately http://openelections.net/faq/ does not specify either. Having a license for the data is crucial for other projects to re-use your data. 

In case you have not yet decided on a license, I would suggest CC0 (https://creativecommons.org/publicdomain/zero/1.0/) as generally suitable for data.

**Comment by dwillis** [comment]
@hroest Thanks for your kind words about the project. Since all of the data here originates with state and local governments, it is already in the public domain.

**Comment by hroest** [comment]
@dwillis I would suggest to make this more clear, to data consumers as well as volunteers. I am not a lawyer but someone could make the argument that the work of assembling the data puts it under copyright and its best to be very clear about these things. I think this will be especially important if you go outside the US since copyright laws differ by country and it always helps to be explicit (see https://en.wikipedia.org/wiki/Database_right). Maybe you could add a point to the FAQ to specify its all public domain?

**Comment by dwillis** [comment]
@hroest We'll look at adding such language; I would only say that in the seven-plus years this project has been in existence you are the first person to raise this as a potential barrier to use.

**Comment by zstumgoren** [comment]
Howdy @dwillis. Sorry for the random chime-in but perhaps we can make quick work of this issue by adopting the [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/). That effectively allows anyone to use the data (including for commercial purposes) but requires them to cite us. JHU recently adopted that license for their COVID19 data (see [terms of use at bottom of this repo](https://github.com/CSSEGISandData/COVID-19)).

The only issue I could foresee for us is if any of the source agencies have themselves licensed the data under particular terms, in which case we may need to carve out exceptions as needed. But as you mentioned earlier in thread, our data is generally public domain, so hopefully the CC 4 license will cover us across the board.

Thoughts?

**Comment by dwillis** [comment]
@zstumgoren That works for me. We've not had any of the source agencies claim that the data is licensed in any way.

**Comment by dwillis** [comment]
Ok, we've added that to the FAQ: http://openelections.net/faq/
