### ISSUE TITLE
Suspicious occurrence of "Mississippi" in CA datasource

### ISSUE THREAD

**Issue by warwickmm** [openelections/openelections-core#282]
In `us/ca/datasource.py`, there is an occurrence of `"Mississippi"` that looks suspicious:

https://github.com/openelections/openelections-core/blob/20afcb5687cdb17538574dc9a549daaf6dbff4d1/openelex/us/ca/datasource.py#L65-L72

Is this on purpose, or a possible copy/paste bug?

**Comment by dwillis** [comment]
@warwickmm it's a copy and paste bug, thanks!

**Comment by warwickmm** [comment]
Thanks @dwillis.  Should "Mississippi" simply be replaced with "California"?  If so, I can make that change.

**Comment by dwillis** [comment]
@warwickmm it can, yes, thanks!
